import { z } from 'zod';

export const RecordCoupleSchema = z.object({
  id: z.string().uuid().optional(),
  workPreference: z.string(),
  externalCouple: z.boolean(),
  cookCouple: z.boolean(),
  womanName: z.string(),
  womanNickname: z.string(),
  womanPhone: z.string(),
  womanInstagram: z.string(),
  womanBirthDate: z.string(),
  coursesOneDone: z.string().nullish(),
  coursesTwoDone: z.string().nullish(),
  coursesThreeDone: z.string().nullish(),
  coursesDone: z.string(),
  currentGroupFunction: z.string(),
  participatedOtherGroups: z.string(),
  womanSpiritualLife: z.array(z.string()),
  familyLife: z.string(),
  religiousWeddingDate: z.string(),
  participatedInRetreat: z.boolean(),
  motivationToParticipate: z.string(),
  parishIndication: z.array(z.string()),
  recordId: z.string().optional(),
});
